var hierarchy =
[
    [ "std::exception", null, [
      [ "YUIException", "classYUIException.html", [
        [ "YUIButtonRoleMismatchException", "classYUIButtonRoleMismatchException.html", null ],
        [ "YUICantLoadAnyUIException", "classYUICantLoadAnyUIException.html", null ],
        [ "YUIDialogStackingOrderException", "classYUIDialogStackingOrderException.html", null ],
        [ "YUIIndexOutOfRangeException", "classYUIIndexOutOfRangeException.html", null ],
        [ "YUIInvalidChildException< YWidget >", "classYUIInvalidChildException.html", null ],
        [ "YUIInvalidDimensionException", "classYUIInvalidDimensionException.html", null ],
        [ "YUIInvalidWidgetException", "classYUIInvalidWidgetException.html", null ],
        [ "YUINoDialogException", "classYUINoDialogException.html", null ],
        [ "YUINullPointerException", "classYUINullPointerException.html", null ],
        [ "YUIOutOfMemoryException", "classYUIOutOfMemoryException.html", null ],
        [ "YUIPluginException", "classYUIPluginException.html", null ],
        [ "YUIPropertyException", "classYUIPropertyException.html", [
          [ "YUIBadPropertyArgException", "classYUIBadPropertyArgException.html", null ],
          [ "YUIPropertyTypeMismatchException", "classYUIPropertyTypeMismatchException.html", null ],
          [ "YUISetReadOnlyPropertyException", "classYUISetReadOnlyPropertyException.html", null ],
          [ "YUIUnknownPropertyException", "classYUIUnknownPropertyException.html", null ]
        ] ],
        [ "YUISyntaxErrorException", "classYUISyntaxErrorException.html", null ],
        [ "YUITooManyChildrenException< YWidget >", "classYUITooManyChildrenException.html", null ],
        [ "YUIUnsupportedWidgetException", "classYUIUnsupportedWidgetException.html", null ],
        [ "YUIWidgetNotFoundException", "classYUIWidgetNotFoundException.html", null ]
      ] ]
    ] ],
    [ "boost::noncopyable", null, [
      [ "ImplPtr< YTablePrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YRadioButtonGroupPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YMultiLineEditPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YDateFieldPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YSliderPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YDumbTabPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YTableHeaderPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YImagePrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YSelectionBoxPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YMenuBarPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YLabelPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YWizardPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YMenuWidgetPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YIntFieldPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YFramePrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YContextMenuPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YBarGraphPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YGraphPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YDialogSpyPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YPushButtonPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YProgressBarPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YMultiProgressMeterPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YItemSelectorPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YCommandLinePrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YTreePrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YPropertyEditorPriv >", "classImplPtr.html", null ],
      [ "ImplPtr< YMultiSelectionBoxPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YDownloadProgressPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YComboBoxPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YTimezoneSelectorPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YLogViewPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YUILogPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YInputFieldPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YCheckBoxPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YEmptyPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YSpacingPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YRichTextPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YRadioButtonPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YPartitionSplitterPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YMenuButtonPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YDialogPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YCheckBoxFramePrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YBusyIndicatorPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YApplicationPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YWidgetPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YTimeFieldPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YSquashPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YSimpleInputFieldPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YButtonBoxPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YSelectionWidgetPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YLayoutBoxPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YEventFilterPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< YAlignmentPrivate >", "classImplPtr.html", null ],
      [ "ImplPtr< _Impl >", "classImplPtr.html", null ]
    ] ],
    [ "OptimizeChanges", "classOptimizeChanges.html", null ],
    [ "boost::ordered_field_operators", null, [
      [ "FSize", "classFSize.html", null ]
    ] ],
    [ "std::streambuf", null, [
      [ "YUILogBuffer", "classYUILogBuffer.html", null ]
    ] ],
    [ "TreeItem< PAYLOAD >", "classTreeItem.html", [
      [ "SortedTreeItem< PAYLOAD >", "classSortedTreeItem.html", null ]
    ] ],
    [ "boost::unit_steppable", null, [
      [ "FSize", "classFSize.html", null ]
    ] ],
    [ "YAlignmentPrivate", "structYAlignmentPrivate.html", null ],
    [ "YApplication", "classYApplication.html", null ],
    [ "YApplicationPrivate", "structYApplicationPrivate.html", null ],
    [ "YBarGraphMultiUpdate", "classYBarGraphMultiUpdate.html", null ],
    [ "YBarGraphPrivate", "structYBarGraphPrivate.html", null ],
    [ "YBarGraphSegment", "classYBarGraphSegment.html", null ],
    [ "YBothDim< T >", "classYBothDim.html", null ],
    [ "YBothDim< bool >", "classYBothDim.html", null ],
    [ "YBothDim< int >", "classYBothDim.html", null ],
    [ "YBothDim< YAlignmentType >", "classYBothDim.html", null ],
    [ "YBuiltinCaller", "classYBuiltinCaller.html", null ],
    [ "YBusyIndicatorPrivate", "structYBusyIndicatorPrivate.html", null ],
    [ "YButtonBoxLayoutPolicy", "structYButtonBoxLayoutPolicy.html", null ],
    [ "YButtonBoxMargins", "structYButtonBoxMargins.html", null ],
    [ "YButtonBoxPrivate", "structYButtonBoxPrivate.html", null ],
    [ "YCheckBoxFramePrivate", "structYCheckBoxFramePrivate.html", null ],
    [ "YCheckBoxPrivate", "structYCheckBoxPrivate.html", null ],
    [ "YChildrenManager< T >", "classYChildrenManager.html", [
      [ "YChildrenRejector< T >", "classYChildrenRejector.html", null ],
      [ "YSingleChildManager< T >", "classYSingleChildManager.html", null ]
    ] ],
    [ "YCodeLocation", "classYCodeLocation.html", null ],
    [ "YColor", "classYColor.html", null ],
    [ "YComboBoxPrivate", "structYComboBoxPrivate.html", null ],
    [ "YCommandLine", "classYCommandLine.html", null ],
    [ "YCommandLinePrivate", "structYCommandLinePrivate.html", null ],
    [ "YContextMenuPrivate", "structYContextMenuPrivate.html", null ],
    [ "YDateFieldPrivate", "structYDateFieldPrivate.html", null ],
    [ "YDialogPrivate", "structYDialogPrivate.html", null ],
    [ "YDialogSpy", "classYDialogSpy.html", null ],
    [ "YDialogSpyPrivate", "classYDialogSpyPrivate.html", null ],
    [ "YDownloadProgressPrivate", "structYDownloadProgressPrivate.html", null ],
    [ "YDumbTabPrivate", "structYDumbTabPrivate.html", null ],
    [ "YEmptyPrivate", "structYEmptyPrivate.html", null ],
    [ "YEnvVar", "classYEnvVar.html", null ],
    [ "YEvent", "classYEvent.html", [
      [ "YCancelEvent", "classYCancelEvent.html", null ],
      [ "YDebugEvent", "classYDebugEvent.html", null ],
      [ "YKeyEvent", "classYKeyEvent.html", null ],
      [ "YMenuEvent", "classYMenuEvent.html", null ],
      [ "YSpecialKeyEvent", "classYSpecialKeyEvent.html", null ],
      [ "YTimeoutEvent", "classYTimeoutEvent.html", null ],
      [ "YWidgetEvent", "classYWidgetEvent.html", null ]
    ] ],
    [ "YEventFilter", "classYEventFilter.html", [
      [ "YHelpButtonHandler", "classYHelpButtonHandler.html", null ],
      [ "YRelNotesButtonHandler", "classYRelNotesButtonHandler.html", null ]
    ] ],
    [ "YEventFilterPrivate", "structYEventFilterPrivate.html", null ],
    [ "YExternalWidgetFactory", "classYExternalWidgetFactory.html", null ],
    [ "YExternalWidgets", "classYExternalWidgets.html", null ],
    [ "YExternalWidgetsTerminator", "classYExternalWidgetsTerminator.html", null ],
    [ "YFramePrivate", "structYFramePrivate.html", null ],
    [ "YGraphPrivate", "structYGraphPrivate.html", null ],
    [ "YIconLoader", "classYIconLoader.html", null ],
    [ "YImagePrivate", "structYImagePrivate.html", null ],
    [ "YInputFieldPrivate", "structYInputFieldPrivate.html", null ],
    [ "YIntFieldPrivate", "structYIntFieldPrivate.html", null ],
    [ "YItem", "classYItem.html", [
      [ "YDescribedItem", "classYDescribedItem.html", null ],
      [ "YTreeItem", "classYTreeItem.html", [
        [ "YMenuItem", "classYMenuItem.html", null ],
        [ "YTableItem", "classYTableItem.html", null ],
        [ "YWidgetTreeItem", "classYWidgetTreeItem.html", null ]
      ] ]
    ] ],
    [ "YItemCustomStatus", "classYItemCustomStatus.html", null ],
    [ "YItemSelectorPrivate", "structYItemSelectorPrivate.html", null ],
    [ "YLabelPrivate", "structYLabelPrivate.html", null ],
    [ "YLayoutBoxPrivate", "structYLayoutBoxPrivate.html", null ],
    [ "YLogViewPrivate", "structYLogViewPrivate.html", null ],
    [ "YMacro", "classYMacro.html", null ],
    [ "YMacroPlayer", "classYMacroPlayer.html", null ],
    [ "YMacroRecorder", "classYMacroRecorder.html", null ],
    [ "YMenuBarPrivate", "structYMenuBarPrivate.html", null ],
    [ "YMenuButtonPrivate", "structYMenuButtonPrivate.html", null ],
    [ "YMenuWidgetPrivate", "structYMenuWidgetPrivate.html", null ],
    [ "YMultiLineEditPrivate", "structYMultiLineEditPrivate.html", null ],
    [ "YMultiProgressMeterPrivate", "structYMultiProgressMeterPrivate.html", null ],
    [ "YMultiSelectionBoxPrivate", "structYMultiSelectionBoxPrivate.html", null ],
    [ "YOptionalWidgetFactory", "classYOptionalWidgetFactory.html", null ],
    [ "YPartitionSplitterPrivate", "structYPartitionSplitterPrivate.html", null ],
    [ "YPath", "classYPath.html", null ],
    [ "YPerThreadLogInfo", "structYPerThreadLogInfo.html", null ],
    [ "YPopupInternal", "classYPopupInternal.html", null ],
    [ "YProgressBarPrivate", "structYProgressBarPrivate.html", null ],
    [ "YProperty", "classYProperty.html", null ],
    [ "YPropertyEditor", "classYPropertyEditor.html", null ],
    [ "YPropertyEditorPriv", "classYPropertyEditorPriv.html", null ],
    [ "YPropertySet", "classYPropertySet.html", null ],
    [ "YPropertyValue", "classYPropertyValue.html", null ],
    [ "YPushButtonPrivate", "structYPushButtonPrivate.html", null ],
    [ "YRadioButtonGroupPrivate", "structYRadioButtonGroupPrivate.html", null ],
    [ "YRadioButtonPrivate", "structYRadioButtonPrivate.html", null ],
    [ "YRichTextPrivate", "structYRichTextPrivate.html", null ],
    [ "YSelectionBoxPrivate", "structYSelectionBoxPrivate.html", null ],
    [ "YSelectionWidgetPrivate", "structYSelectionWidgetPrivate.html", null ],
    [ "YSettings", "classYSettings.html", null ],
    [ "YShortcut", "classYShortcut.html", [
      [ "YItemShortcut", "classYItemShortcut.html", null ]
    ] ],
    [ "YShortcutManager", "classYShortcutManager.html", null ],
    [ "YSimpleEventHandler", "classYSimpleEventHandler.html", null ],
    [ "YSimpleInputFieldPrivate", "structYSimpleInputFieldPrivate.html", null ],
    [ "YSliderPrivate", "structYSliderPrivate.html", null ],
    [ "YSpacingPrivate", "structYSpacingPrivate.html", null ],
    [ "YSquashPrivate", "structYSquashPrivate.html", null ],
    [ "YStringTree", "classYStringTree.html", [
      [ "YRpmGroupsTree", "classYRpmGroupsTree.html", null ]
    ] ],
    [ "YTableCell", "classYTableCell.html", null ],
    [ "YTableHeader", "classYTableHeader.html", null ],
    [ "YTableHeaderPrivate", "structYTableHeaderPrivate.html", null ],
    [ "YTablePrivate", "structYTablePrivate.html", null ],
    [ "YTimeFieldPrivate", "structYTimeFieldPrivate.html", null ],
    [ "YTimezoneSelectorPrivate", "classYTimezoneSelectorPrivate.html", null ],
    [ "YTransText", "classYTransText.html", null ],
    [ "YTreePrivate", "structYTreePrivate.html", null ],
    [ "YUI", "classYUI.html", null ],
    [ "YUILoader", "classYUILoader.html", null ],
    [ "YUILog", "classYUILog.html", null ],
    [ "YUILogPrivate", "structYUILogPrivate.html", null ],
    [ "YUIPlugin", "classYUIPlugin.html", [
      [ "YGraphPlugin", "classYGraphPlugin.html", null ],
      [ "YPackageSelectorPlugin", "classYPackageSelectorPlugin.html", null ]
    ] ],
    [ "YWidget", "classYWidget.html", [
      [ "YBarGraph", "classYBarGraph.html", null ],
      [ "YBusyIndicator", "classYBusyIndicator.html", null ],
      [ "YButtonBox", "classYButtonBox.html", null ],
      [ "YCheckBox", "classYCheckBox.html", null ],
      [ "YDownloadProgress", "classYDownloadProgress.html", null ],
      [ "YEmpty", "classYEmpty.html", null ],
      [ "YGraph", "classYGraph.html", null ],
      [ "YImage", "classYImage.html", null ],
      [ "YInputField", "classYInputField.html", null ],
      [ "YIntField", "classYIntField.html", [
        [ "YSlider", "classYSlider.html", null ]
      ] ],
      [ "YLabel", "classYLabel.html", null ],
      [ "YLayoutBox", "classYLayoutBox.html", null ],
      [ "YLogView", "classYLogView.html", null ],
      [ "YMultiLineEdit", "classYMultiLineEdit.html", null ],
      [ "YMultiProgressMeter", "classYMultiProgressMeter.html", null ],
      [ "YPackageSelector", "classYPackageSelector.html", null ],
      [ "YPartitionSplitter", "classYPartitionSplitter.html", null ],
      [ "YProgressBar", "classYProgressBar.html", null ],
      [ "YPushButton", "classYPushButton.html", null ],
      [ "YRadioButton", "classYRadioButton.html", null ],
      [ "YRichText", "classYRichText.html", null ],
      [ "YSelectionWidget", "classYSelectionWidget.html", [
        [ "YComboBox", "classYComboBox.html", null ],
        [ "YContextMenu", "classYContextMenu.html", null ],
        [ "YDumbTab", "classYDumbTab.html", null ],
        [ "YItemSelector", "classYItemSelector.html", null ],
        [ "YMenuWidget", "classYMenuWidget.html", [
          [ "YMenuBar", "classYMenuBar.html", null ],
          [ "YMenuButton", "classYMenuButton.html", null ]
        ] ],
        [ "YMultiSelectionBox", "classYMultiSelectionBox.html", null ],
        [ "YSelectionBox", "classYSelectionBox.html", null ],
        [ "YTable", "classYTable.html", null ],
        [ "YTree", "classYTree.html", null ]
      ] ],
      [ "YSimpleInputField", "classYSimpleInputField.html", [
        [ "YDateField", "classYDateField.html", null ],
        [ "YTimeField", "classYTimeField.html", null ]
      ] ],
      [ "YSingleChildContainerWidget", "classYSingleChildContainerWidget.html", [
        [ "YAlignment", "classYAlignment.html", null ],
        [ "YCheckBoxFrame", "classYCheckBoxFrame.html", null ],
        [ "YDialog", "classYDialog.html", null ],
        [ "YFrame", "classYFrame.html", null ],
        [ "YRadioButtonGroup", "classYRadioButtonGroup.html", null ],
        [ "YReplacePoint", "classYReplacePoint.html", null ],
        [ "YSquash", "classYSquash.html", null ]
      ] ],
      [ "YSpacing", "classYSpacing.html", null ],
      [ "YTimezoneSelector", "classYTimezoneSelector.html", null ],
      [ "YWizard", "classYWizard.html", null ]
    ] ],
    [ "YWidgetFactory", "classYWidgetFactory.html", null ],
    [ "YWidgetID", "classYWidgetID.html", [
      [ "YStringWidgetID", "classYStringWidgetID.html", null ]
    ] ],
    [ "YWidgetPrivate", "structYWidgetPrivate.html", null ],
    [ "YWizardPrivate", "structYWizardPrivate.html", null ]
];