SET( ${TARGETLIB}_SOURCES
  NCPackageSelector.cc
  NCPackageSelectorPluginImpl.cc
  NCPackageSelectorStart.cc
  NCPkgFilterClassification.cc
  NCPkgFilterInstSummary.cc
  NCPkgFilterLocale.cc
  NCPkgFilterMain.cc
  NCPkgFilterPattern.cc
  NCPkgFilterRPMGroups.cc
  NCPkgFilterRepo.cc
  NCPkgFilterService.cc
  NCPkgFilterSearch.cc
  NCPkgMenuAction.cc
  NCPkgMenuConfig.cc
  NCPkgMenuDeps.cc
  NCPkgMenuExtras.cc
  NCPkgMenuFilter.cc
  NCPkgMenuHelp.cc
  NCPkgMenuView.cc
  NCPkgPackageDetails.cc
  NCPkgPatchSearch.cc
  NCPkgPopupDeps.cc
  NCPkgPopupDescr.cc
  NCPkgPopupDiskspace.cc
  NCPkgPopupTable.cc
  NCPkgSearchSettings.cc
  NCPkgSelMapper.cc
  NCPkgStatusStrategy.cc
  NCPkgStrings.cc
  NCPkgTable.cc
)

SET( ${TARGETLIB}_HEADERS
  NCPackageSelector.h
  NCPackageSelectorPluginImpl.h
  NCPackageSelectorStart.h
  NCPkgFilterClassification.h
  NCPkgFilterInstSummary.h
  NCPkgFilterLocale.h
  NCPkgFilterMain.h
  NCPkgFilterPattern.h
  NCPkgFilterRPMGroups.h
  NCPkgFilterRepo.h
  NCPkgFilterService.h
  NCPkgFilterSearch.h
  NCPkgMenuAction.h
  NCPkgMenuConfig.h
  NCPkgMenuDeps.h
  NCPkgMenuExtras.h
  NCPkgMenuFilter.h
  NCPkgMenuHelp.h
  NCPkgMenuView.h
  NCPkgPackageDetails.h
  NCPkgPatchSearch.h
  NCPkgPopupDeps.h
  NCPkgPopupDescr.h
  NCPkgPopupDiskspace.h
  NCPkgPopupTable.h
  NCPkgSearchSettings.h
  NCPkgSelMapper.h
  NCPkgStatusStrategy.h
  NCPkgStrings.h
  NCPkgTable.h
  NCZypp.h
)
