//-----------------------------------------------------------------
// generated by lang2encoding.tab
//-----------------------------------------------------------------
#include <string>

std::string language2encoding( std::string lang )
{
  using std::string;
  lang = ":" + lang + ":";
  if ( string( ":ca:da:de:en:es:fi:fr:gl:is:it:nl:no:pt:sv:" ).find( lang ) != string::npos )
    return "ISO-8859-1";
  else if ( string( ":lt:" ).find( lang ) != string::npos )
    return "ISO-8859-13";
  else if ( string( ":cs:hr:hu:pl:ro:sk:sl:" ).find( lang ) != string::npos )
    return "ISO-8859-2";
  else if ( string( ":ru:" ).find( lang ) != string::npos )
    return "ISO-8859-5";
  else if ( string( ":el:" ).find( lang ) != string::npos )
    return "ISO-8859-7";
  else if ( string( ":iw:" ).find( lang ) != string::npos )
    return "ISO-8859-8";
  else if ( string( ":tr:" ).find( lang ) != string::npos )
    return "ISO-8859-9";
  else if ( string( ":ja:" ).find( lang ) != string::npos )
    return "eucJP";
  return "";
}
//-----------------------------------------------------------------
