/*---------------------------------------------------------------------\
|								       |
|		       __   __	  ____ _____ ____		       |
|		       \ \ / /_ _/ ___|_   _|___ \		       |
|			\ V / _` \___ \ | |   __) |		       |
|			 | | (_| |___) || |  / __/		       |
|			 |_|\__,_|____/ |_| |_____|		       |
|								       |
|				core system			       |
|							 (C) SuSE GmbH |
\----------------------------------------------------------------------/

   File:       NCstyle.rxvt.h

   Author:     Generated by class NCstyle

/-*/

#ifndef NCstyle_rxvt_h
#define NCstyle_rxvt_h

#include "NCstyle.h"

inline void NCstyleInit_rxvt( vector<NCstyle::Style> & styleSet )
{
    //=================================================================
    // init global attributes
    //=================================================================
    NCattrset * attrset( &styleSet[NCstyle::DefaultStyle].getAttrGlobal() );
    attrset->setAttr( NCstyle::AppTitle, 7936 );
    attrset->setAttr( NCstyle::AppText, 1024 );
    //=================================================================
    // init local attributes
    //=================================================================
    // DefaultStyle
    attrset = &styleSet[NCstyle::DefaultStyle].getAttrLocal();
    attrset->setAttr( NCstyle::DialogBorder, 1024 );
    attrset->setAttr( NCstyle::DialogTitle, 1024 );
    attrset->setAttr( NCstyle::DialogActiveBorder, 1024 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveTitle, 1024 | A_BOLD );
    attrset->setAttr( NCstyle::DialogText, 1024 );
    attrset->setAttr( NCstyle::DialogHeadline, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::DialogDisabled, 0 );
    attrset->setAttr( NCstyle::DialogPlain, 1024 );
    attrset->setAttr( NCstyle::DialogLabel, 1024 );
    attrset->setAttr( NCstyle::DialogData, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::DialogHint, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::DialogScrl, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActivePlain, 7936 );
    attrset->setAttr( NCstyle::DialogActiveLabel, 7936 );
    attrset->setAttr( NCstyle::DialogActiveData, 7936 );
    attrset->setAttr( NCstyle::DialogActiveHint, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveScrl, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::DialogFramePlain, 1024 );
    attrset->setAttr( NCstyle::DialogFrameLabel, 1024 );
    attrset->setAttr( NCstyle::DialogFrameData, 1024 );
    attrset->setAttr( NCstyle::DialogFrameHint, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::DialogFrameScrl, 1024 );
    attrset->setAttr( NCstyle::DialogActiveFramePlain, 1024 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveFrameLabel, 7936 );
    attrset->setAttr( NCstyle::DialogActiveFrameData, 1024 );
    attrset->setAttr( NCstyle::DialogActiveFrameHint, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveFrameScrl, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::ListTitle, 1024 );
    attrset->setAttr( NCstyle::ListPlain, 1024 );
    attrset->setAttr( NCstyle::ListLabel, 1024 );
    attrset->setAttr( NCstyle::ListData, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::ListHint, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::ListSelPlain, 1024 );
    attrset->setAttr( NCstyle::ListSelLabel, 1024 );
    attrset->setAttr( NCstyle::ListSelData, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::ListSelHint, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveTitle, 1024 );
    attrset->setAttr( NCstyle::ListActivePlain, 1024 );
    attrset->setAttr( NCstyle::ListActiveLabel, 1024 );
    attrset->setAttr( NCstyle::ListActiveData, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveHint, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveSelPlain, 7936 );
    attrset->setAttr( NCstyle::ListActiveSelLabel, 7936 );
    attrset->setAttr( NCstyle::ListActiveSelData, 7936 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveSelHint, 6144 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextPlain, 1792 );
    //Need to set foreground color explicitely, otherwise urxvt will display
    //black font on black background. This solution sucks, but cannot find
    //any better (#336060)
    attrset->setFg( NCstyle::RichTextPlain, 7 );
    attrset->setAttr( NCstyle::RichTextTitle, 512 );
    attrset->setAttr( NCstyle::RichTextLink, 768 );
    attrset->setAttr( NCstyle::RichTextArmedlink, 768 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextActiveArmedlink, 1024 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextVisitedLink, 3 );
    attrset->setAttr( NCstyle::RichTextB, 0 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextI, 0 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextT, 256 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextBI, 512 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextBT, 256 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextIT, 512 );
    attrset->setAttr( NCstyle::RichTextBIT, 14848 );
    attrset->setAttr( NCstyle::ProgbarCh, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::ProgbarBgch, 32 | A_BOLD );
    attrset->setAttr( NCstyle::TextCursor, 7936 | A_BLINK );
    // InfoStyle
    attrset = &styleSet[NCstyle::InfoStyle].getAttrLocal();
    attrset->setAttr( NCstyle::DialogBorder, 5888 );
    attrset->setAttr( NCstyle::DialogTitle, 5888 );
    attrset->setAttr( NCstyle::DialogActiveBorder, 4096 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveTitle, 4096 | A_BOLD );
    attrset->setAttr( NCstyle::DialogText, 5888 );
    attrset->setAttr( NCstyle::DialogHeadline, 4096 | A_BOLD );
    attrset->setAttr( NCstyle::DialogDisabled, 5376 | A_BOLD );
    attrset->setAttr( NCstyle::DialogPlain, 4096 | A_BOLD );
    attrset->setAttr( NCstyle::DialogLabel, 5888 );
    attrset->setAttr( NCstyle::DialogData, 4096 | A_BOLD );
    attrset->setAttr( NCstyle::DialogHint, 4096 | A_BOLD );
    attrset->setAttr( NCstyle::DialogScrl, 0 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActivePlain, 0 );
    attrset->setAttr( NCstyle::DialogActiveLabel, 0 );
    attrset->setAttr( NCstyle::DialogActiveData, 0 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveHint, 0 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveScrl, 0 );
    attrset->setAttr( NCstyle::DialogFramePlain, 5888 );
    attrset->setAttr( NCstyle::DialogFrameLabel, 5888 );
    attrset->setAttr( NCstyle::DialogFrameData, 5888 );
    attrset->setAttr( NCstyle::DialogFrameHint, 4096 | A_BOLD );
    attrset->setAttr( NCstyle::DialogFrameScrl, 4096 );
    attrset->setAttr( NCstyle::DialogActiveFramePlain, 4096 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveFrameLabel, 0 );
    attrset->setAttr( NCstyle::DialogActiveFrameData, 5888 );
    attrset->setAttr( NCstyle::DialogActiveFrameHint, 0 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveFrameScrl, 5376 | A_BOLD );
    attrset->setAttr( NCstyle::ListTitle, 5888 );
    attrset->setAttr( NCstyle::ListPlain, 5888 );
    attrset->setAttr( NCstyle::ListLabel, 5888 );
    attrset->setAttr( NCstyle::ListData, 4096 | A_BOLD );
    attrset->setAttr( NCstyle::ListHint, 4096 | A_BOLD );
    attrset->setAttr( NCstyle::ListSelPlain, 5888 );
    attrset->setAttr( NCstyle::ListSelLabel, 5888 );
    attrset->setAttr( NCstyle::ListSelData, 4096 | A_BOLD );
    attrset->setAttr( NCstyle::ListSelHint, 4096 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveTitle, 5888 );
    attrset->setAttr( NCstyle::ListActivePlain, 5888 );
    attrset->setAttr( NCstyle::ListActiveLabel, 5888 );
    attrset->setAttr( NCstyle::ListActiveData, 4096 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveHint, 4096 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveSelPlain, 0 );
    attrset->setAttr( NCstyle::ListActiveSelLabel, 0 );
    attrset->setAttr( NCstyle::ListActiveSelData, 0 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveSelHint, 0 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextPlain, 0 );
    attrset->setFg( NCstyle::RichTextPlain, 7 );
    attrset->setAttr( NCstyle::RichTextTitle, 15360 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextLink, 768 );
    attrset->setAttr( NCstyle::RichTextArmedlink, 768 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextActiveArmedlink, 1024 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextVisitedLink, 3 );
    attrset->setAttr( NCstyle::RichTextB, 0 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextI, 0 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextT, 256 );
    attrset->setAttr( NCstyle::RichTextBI, 512 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextBT, 256 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextIT, 256 );
    attrset->setAttr( NCstyle::RichTextBIT, 256 | A_BOLD );
    attrset->setAttr( NCstyle::ProgbarCh, 0x1720 );
    attrset->setAttr( NCstyle::ProgbarBgch, 16160 );
    attrset->setAttr( NCstyle::TextCursor, 7936 | A_BLINK );
    // WarnStyle
    attrset = &styleSet[NCstyle::WarnStyle].getAttrLocal();
    attrset->setAttr( NCstyle::DialogBorder, 3840 );
    attrset->setAttr( NCstyle::DialogTitle, 3840 );
    attrset->setAttr( NCstyle::DialogActiveBorder, 2048 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveTitle, 2048 | A_BOLD );
    attrset->setAttr( NCstyle::DialogText, 3840 );
    attrset->setAttr( NCstyle::DialogHeadline, 2048 | A_BOLD );
    attrset->setAttr( NCstyle::DialogDisabled, 3584 | A_BOLD );
    attrset->setAttr( NCstyle::DialogPlain, 3840 );
    attrset->setAttr( NCstyle::DialogLabel, 3840 );
    attrset->setAttr( NCstyle::DialogData, 2048 | A_BOLD );
    attrset->setAttr( NCstyle::DialogHint, 2048 | A_BOLD );
    attrset->setAttr( NCstyle::DialogScrl, 0 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActivePlain, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveLabel, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveData, 0 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveHint, 0 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveScrl, 0 | A_BOLD );
    attrset->setAttr( NCstyle::DialogFramePlain, 3840 );
    attrset->setAttr( NCstyle::DialogFrameLabel, 3840 );
    attrset->setAttr( NCstyle::DialogFrameData, 3840 );
    attrset->setAttr( NCstyle::DialogFrameHint, 2048 | A_BOLD );
    attrset->setAttr( NCstyle::DialogFrameScrl, 3584 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveFramePlain, 2048 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveFrameLabel, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveFrameData, 3840 );
    attrset->setAttr( NCstyle::DialogActiveFrameHint, 0 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveFrameScrl, 3584 | A_BOLD );
    attrset->setAttr( NCstyle::ListTitle, 3840 );
    attrset->setAttr( NCstyle::ListPlain, 3840 );
    attrset->setAttr( NCstyle::ListLabel, 3840 );
    attrset->setAttr( NCstyle::ListData, 2048 | A_BOLD );
    attrset->setAttr( NCstyle::ListHint, 2048 | A_BOLD );
    attrset->setAttr( NCstyle::ListSelPlain, 3840 );
    attrset->setAttr( NCstyle::ListSelLabel, 3840 );
    attrset->setAttr( NCstyle::ListSelData, 2048 | A_BOLD );
    attrset->setAttr( NCstyle::ListSelHint, 2048 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveTitle, 3840 );
    attrset->setAttr( NCstyle::ListActivePlain, 3840 );
    attrset->setAttr( NCstyle::ListActiveLabel, 3840 );
    attrset->setAttr( NCstyle::ListActiveData, 2048 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveHint, 2048 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveSelPlain, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveSelLabel, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveSelData, 0 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveSelHint, 0 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextPlain, 0 );
    attrset->setFg( NCstyle::RichTextPlain, 7 );
    attrset->setAttr( NCstyle::RichTextTitle, 15360 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextLink, 768 );
    attrset->setAttr( NCstyle::RichTextArmedlink, 768 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextActiveArmedlink, 1024 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextVisitedLink, 3 );
    attrset->setAttr( NCstyle::RichTextB, 0 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextI, 0 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextT, 256 );
    attrset->setAttr( NCstyle::RichTextBI, 512 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextBT, 256 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextIT, 256 );
    attrset->setAttr( NCstyle::RichTextBIT, 256 | A_BOLD );
    attrset->setAttr( NCstyle::ProgbarCh, 0x1720 );
    attrset->setAttr( NCstyle::ProgbarBgch, 16160 );
    attrset->setAttr( NCstyle::TextCursor, 7936 | A_BLINK );
    // PopupStyle
    attrset = &styleSet[NCstyle::PopupStyle].getAttrLocal();
    attrset->setAttr( NCstyle::DialogBorder, 7936 );
    attrset->setAttr( NCstyle::DialogTitle, 7936 );
    attrset->setAttr( NCstyle::DialogActiveBorder, 6144 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveTitle, 6144 | A_BOLD );
    attrset->setAttr( NCstyle::DialogText, 7936 );
    attrset->setAttr( NCstyle::DialogHeadline, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::DialogDisabled, 7936 | A_BOLD );
    attrset->setAttr( NCstyle::DialogPlain, 7936 );
    attrset->setAttr( NCstyle::DialogLabel, 7936 );
    attrset->setAttr( NCstyle::DialogData, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::DialogHint, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::DialogScrl, 1024 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActivePlain, 1024 );
    attrset->setAttr( NCstyle::DialogActiveLabel, 1024 );
    attrset->setAttr( NCstyle::DialogActiveData, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveHint, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveScrl, 1024 | A_BOLD );
    attrset->setAttr( NCstyle::DialogFramePlain, 7936 );
    attrset->setAttr( NCstyle::DialogFrameLabel, 7936 );
    attrset->setAttr( NCstyle::DialogFrameData, 13056 );
    attrset->setAttr( NCstyle::DialogFrameHint, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::DialogFrameScrl, 7936 );
    attrset->setAttr( NCstyle::DialogActiveFramePlain, 6144 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveFrameLabel, 1024 );
    attrset->setAttr( NCstyle::DialogActiveFrameData, 7936 );
    attrset->setAttr( NCstyle::DialogActiveFrameHint, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::DialogActiveFrameScrl, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::ListTitle, 7936 );
    attrset->setAttr( NCstyle::ListPlain, 7936 );
    attrset->setAttr( NCstyle::ListLabel, 7936 );
    attrset->setAttr( NCstyle::ListData, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::ListHint, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::ListSelPlain, 6912 );
    attrset->setAttr( NCstyle::ListSelLabel, 6912 );
    attrset->setAttr( NCstyle::ListSelData, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::ListSelHint, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveTitle, 7936 );
    attrset->setAttr( NCstyle::ListActivePlain, 7936 );
    attrset->setAttr( NCstyle::ListActiveLabel, 7936 );
    attrset->setAttr( NCstyle::ListActiveData, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveHint, 7168 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveSelPlain, 1024 );
    attrset->setAttr( NCstyle::ListActiveSelLabel, 1024 );
    attrset->setAttr( NCstyle::ListActiveSelData, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::ListActiveSelHint, 1536 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextPlain, 0 );
    attrset->setFg( NCstyle::RichTextPlain, 7 );
    attrset->setAttr( NCstyle::RichTextTitle, 15360 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextLink, 768 );
    attrset->setAttr( NCstyle::RichTextArmedlink, 768 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextActiveArmedlink, 1024 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextVisitedLink, 3 );
    attrset->setAttr( NCstyle::RichTextB, 0 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextI, 0 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextT, 256 );
    attrset->setAttr( NCstyle::RichTextBI, 512 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextBT, 256 | A_BOLD );
    attrset->setAttr( NCstyle::RichTextIT, 256 );
    attrset->setAttr( NCstyle::RichTextBIT, 256 | A_BOLD );
    attrset->setAttr( NCstyle::ProgbarCh, 0x1720 );
    attrset->setAttr( NCstyle::ProgbarBgch, 16160 );
    attrset->setAttr( NCstyle::TextCursor, 7936 | A_BLINK );
}

#endif // NCstyle_rxvt_h
