#
# Makefile.cvs
#

LIB = $(shell y2tool get-lib)

PREFIX = /usr

configure: 
	mkdir build ;\
	cd build ;\
	cmake -DCMAKE_INSTALL_PREFIX=$(PREFIX) -DLIB=$(LIB) ..

install: configure
	cd build; \
	make && make install

reconf: 
	cd build ;\
	cmake rebuild_cache
