set(CMAKE_AUTORCC ON)

SET( ${TARGETLIB}_WRAP_UI
  QHelpDialog.ui
  QStyleEditor.ui
)

SET( ${TARGETLIB}_SOURCES
     QY2CharValidator.cc
     QY2ComboTabWidget.cc
     QY2DiskUsageList.cc
     QY2HelpDialog.cc
     QY2RelNotesDialog.cc
     QY2ListView.cc
     QY2Styler.cc
     YQAlignment.cc
     YQApplication.cc
     YQBarGraph.cc
     YQBusyIndicator.cc
     YQButtonBox.cc
     YQCheckBox.cc
     YQCheckBoxFrame.cc
     YQComboBox.cc
     YQContextMenu.cc
     YQDateField.cc
     YQDialog.cc
     YQDownloadProgress.cc
     YQDumbTab.cc
     YQEmpty.cc
     YQFrame.cc
     YQGenericButton.cc
     YQImage.cc
     YQInputField.cc
     YQIntField.cc
     YQItemSelector.cc
     YQLabel.cc
     YQLayoutBox.cc
     YQLogView.cc
     YQMainWinDock.cc
     YQMenuButton.cc
     YQMultiLineEdit.cc
     YQMultiProgressMeter.cc
     YQMultiSelectionBox.cc
     YQOptionalWidgetFactory.cc
     YQPackageSelectorPluginStub.cc
     YQGraphPluginStub.cc
     YQPartitionSplitter.cc
     YQProgressBar.cc
     YQPushButton.cc
     YQRadioButton.cc
     YQRadioButtonGroup.cc
     YQReplacePoint.cc
     YQRichText.cc
     YQSelectionBox.cc
     YQSignalBlocker.cc
     YQSlider.cc
     YQSpacing.cc
     YQSquash.cc
     YQTable.cc
     YQTimeField.cc
     YQTimezoneSelector.cc
     YQTree.cc
     YQUI.cc
     YQUI_builtins.cc
     YQWidgetCaption.cc
     YQWidgetFactory.cc
     YQWizard.cc
     YQWizardButton.cc
     QY2StyleEditor.cc
     qt_icons.qrc
)

SET( ${TARGETLIB}_HEADERS
  ##### Here go the headers
     utf8.h
     QY2CharValidator.h
     QY2ComboTabWidget.h
     QY2DiskUsageList.h
     QY2HelpDialog.h
     QY2RelNotesDialog.h
     QY2ListView.h
     QY2Styler.h
     YQi18n.h
     YQAlignment.h
     YQApplication.h
     YQBarGraph.h
     YQBusyIndicator.h
     YQButtonBox.h
     YQCheckBox.h
     YQCheckBoxFrame.h
     YQComboBox.h
     YQContextMenu.h
     YQDateField.h
     YQDialog.h
     YQDownloadProgress.h
     YQDumbTab.h
     YQEmpty.h
     YQFrame.h
     YQGenericButton.h
     YQImage.h
     YQInputField.h
     YQIntField.h
     YQItemSelector.h
     YQLabel.h
     YQLayoutBox.h
     YQLogView.h
     YQMainWinDock.h
     YQMenuButton.h
     YQMultiLineEdit.h
     YQMultiProgressMeter.h
     YQMultiSelectionBox.h
     YQOptionalWidgetFactory.h
     YQPackageSelectorPluginIf.h
     YQPackageSelectorPluginStub.h
     YQGraphPluginIf.h
     YQGraphPluginStub.h
     YQPartitionSplitter.h
     YQProgressBar.h
     YQPushButton.h
     YQRadioButton.h
     YQRadioButtonGroup.h
     YQReplacePoint.h
     YQRichText.h
     YQSelectionBox.h
     YQSignalBlocker.h
     YQSlider.h
     YQSpacing.h
     YQSquash.h
     YQTable.h
     YQTimeField.h
     YQTimezoneSelector.h
     YQTree.h
     YQUI.h
     YQWidgetCaption.h
     YQWidgetFactory.h
     YQWizard.h
     YQWizardButton.h
     QY2StyleEditor.h
)

SET( EXAMPLES_LIST
  ##### Here go the examples
)

